# 冲顶大会 iphone6s
debug: false
device: android
ocr_type: baidu
wda_address: '127.0.0.1:8100'
question_x: 45
question_y: 111
question_w: 196
question_h: 43
answer_x: 32
answer_y: 190
answer_w: 230
answer_h: 117
baidu_api_key: BIB1lu6cwZ4EsNzuxtHb1310
baidu_secret_key: rUxuWgz9cd1KpT2BvxmrWfbzhQq0GTzU
